### ISSUE TITLE
After update config file stops working

### ISSUE THREAD

**Issue by Librebowski** [ZFPSystems/tbms#1]
Hey I set up the config file fine, loaded up the browser and everything was fine until I updated the browser. Not sure if it helps but I received the following error code: 

 ###!!! [Parent][MessageChannel] Error: (msgtype=0x2C0086,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

Anyway I would love to get this figured out if there is any other questions let me know. it seems this new update has issues and I can't be the only one.

**Comment by Librebowski** [comment]
I got it figured out make sure to change the following value.

 about:config > browser.tabs.remote.autostart.2;false

Edit: still won't connect, to the network. 

Worked fine before the update but anyone else who updated should be able to reproduce this problem.

**Comment by zfpsupport** [comment]
Great you figured it out and yes Browser update can cause issues, so best to test.

I'll update the README to state this clear.

Thanks for your comments! :)
- Paolo
